<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxwmV3k\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxwmV3k/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFxwmV3k.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFxwmV3k\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFxwmV3k\App_KernelDevDebugContainer([
    'container.build_hash' => 'FxwmV3k',
    'container.build_id' => 'c3c0ae51',
    'container.build_time' => 1580160008,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxwmV3k');
