<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGsSa9ff\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGsSa9ff/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGsSa9ff.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGsSa9ff\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGsSa9ff\App_KernelDevDebugContainer([
    'container.build_hash' => 'GsSa9ff',
    'container.build_id' => 'ce8ad5be',
    'container.build_time' => 1580156731,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGsSa9ff');
