<p>Statistics for daily visits, popular content, etc. Statistics generated by searchbots are ignored</p>

<h3>General</h3>

<div class="help_txt_row"><div class="orbx_help_left_col"><?php echo _L('show_all'); ?></div>
<div class="orbx_help_right_col">Expand table to display full statistics</div></div>

<h3><?php echo _L('visits'); ?></h3>

<div class="help_txt_row"><div class="orbx_help_left_col"></div>
<div class="orbx_help_right_col">Grey line displays the number of daily sessions. The green line displays the number of unique IP addresses per day</div></div>

<h3><?php echo _L('content'); ?></h3>

<div class="help_txt_row"><div class="orbx_help_left_col">URL</div>
<div class="orbx_help_right_col">URL to site's popular content. <strong>Bolded</strong> content is from site's front-end</div></div>

<div class="help_txt_row"><div class="orbx_help_left_col">Number of views</div>
<div class="orbx_help_right_col">Number of content views</div></div>


<h3><?php echo _L('refers'); ?></h3>

<div class="help_txt_row"><div class="orbx_help_left_col">URL</div>
<div class="orbx_help_right_col">URL to external refer which user used to find your website</div></div>

<div class="help_txt_row"><div class="orbx_help_left_col">Number of entries</div>
<div class="orbx_help_right_col">Number of entries from external refers</div></div>

<h3><?php echo _L('keywords'); ?></h3>

<div class="help_txt_row"><div class="orbx_help_left_col">Keyword</div>
<div class="orbx_help_right_col">Keyword which helped user to reach your site through search engine</div></div>

<div class="help_txt_row"><div class="orbx_help_left_col">Number of searches</div>
<div class="orbx_help_right_col">Number of searches for a keyword</div></div>

<h3><?php echo _L('countries'); ?></h3>

<div class="help_txt_row"><div class="orbx_help_left_col">Country</div>
<div class="orbx_help_right_col">Country in which user's computer is located</div></div>

<div class="help_txt_row"><div class="orbx_help_left_col">Number of entries</div>
<div class="orbx_help_right_col">Number of entries for each country</div></div>

<h3>Select a month</h3>

<div class="help_txt_row"><div class="orbx_help_left_col"></div>
<div class="orbx_help_right_col">Preview statics by month (if available)</div></div>