CREATE TABLE IF NOT EXISTS `orbx_mod_inpulls_profile` (
  `id` int(11) NOT NULL auto_increment,
  `pring_id` int(11) NOT NULL default '0',
  `im_here_for` int(11) NOT NULL default '0',
  `currently_im` int(11) NOT NULL default '0',
  `sex_group` int(11) NOT NULL default '0',
  `more_info` text NOT NULL,
  `hobby` text NOT NULL,
  `life_moto` text NOT NULL,
  `im_proud_of` text NOT NULL,
  `life_hero` text NOT NULL,
  `activities` text NOT NULL,
  `favorite_food` text NOT NULL,
  `favorite_book` text NOT NULL,
  `favorite_movie` text NOT NULL,
  `favorite_actor` text NOT NULL,
  `favorite_band` text NOT NULL,
  `favorite_song` text NOT NULL,
  `eye_color` text NOT NULL,
  `hair_color` text NOT NULL,
  `heritage` text NOT NULL,
  `best_physical_feature` text NOT NULL,
  `favorite_drinks` int(11) NOT NULL default '0',
  `what_attracts_you_most` text NOT NULL,
  `hair_length` text NOT NULL,
  `weight` int(11) NOT NULL default '0',
  `height` decimal(12,2) NOT NULL,
  `tattoo_piercings` text NOT NULL,
  `music` int(11) NOT NULL default '0',
  `tags` text NOT NULL,
  `registered` int(11) NOT NULL default '0',
  `sponsored` int(1) NOT NULL default '0',
  `sponsored_category` text NOT NULL,
  `group_memberships` text NOT NULL,
  `sponsored_live_to` int(11) NOT NULL default '0',
  `online_last_activity` int(11) NOT NULL default '0',
  `keywords` text NOT NULL,
  `longitude` varchar(255) NOT NULL,
  `latitude` varchar(255) NOT NULL,
  `treat_girls` int(11) NOT NULL default '0',
  `had_girls` int(11) NOT NULL default '0',
  `crazy_thing_for_girls` text NOT NULL,
  `shopping_with_girl` int(11) NOT NULL default '0',
  `monthly_income` text NOT NULL,
  `special_skills` int(11) NOT NULL default '0',
  `you_in_future` int(11) NOT NULL default '0',
  `message_for_future_girl` text NOT NULL,
  `when_i_was_little` int(11) NOT NULL default '0',
  `all_day` int(11) NOT NULL default '0',
  `from_boyfriend` int(11) NOT NULL default '0',
  `special_skills_girls` int(11) NOT NULL default '0',
  `message_for_future_boy` text NOT NULL ,
  `video` text NOT NULL ,
  `horoscope` int(11) NOT NULL default '0',
  `views` int(11) NOT NULL default '0',
  `inpulls_mail` int(1) NOT NULL default '0',
  `smoker` int(11) NOT NULL default '0',
  `birthday` varchar(4) NOT NULL,
  `last_profile_viewers` text NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `id` (`id`)
);


CREATE TABLE IF NOT EXISTS `orbx_mod_inpulls_mobbing` (
  `id` int(11) NOT NULL auto_increment,
  `user_reg_id` int(11) NOT NULL default '0',
  `mobber_reg_id` int(11) NOT NULL default '0',
  `reason` text NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `id` (`id`)
);

CREATE TABLE IF NOT EXISTS `orbx_mod_inpulls_comments`  (
  `id` int(11) NOT NULL auto_increment,
  `content` text NOT NULL,
  `time` int(11) NOT NULL default '0',
  `author_rid` int(11) NOT NULL default '0',
  `user_rid` int(11) NOT NULL default '0',
  PRIMARY KEY  (`id`)
);