

INSERT INTO `orbicon_sys_iso_639_2_codes` (`id`, `iso_code`, `en`, `fr`) VALUES (1, 'aar', 'Afar', 'afar'),
(2, 'abk', 'Abkhazian', 'abkhaze'),
(3, 'ace', 'Achinese', 'aceh'),
(4, 'ach', 'Acoli', 'acoli'),
(5, 'ada', 'Adangme', 'adangme'),
(6, 'ady', 'Adyghe; Adygei', 'adygh&#233;'),
(7, 'afa', 'Afro-Asiatic (Other)', 'afro-asiatiques, autres langues'),
(8, 'afh', 'Afrihili', 'afrihili'),
(9, 'afr', 'Afrikaans', 'afrikaans'),
(10, 'ain', 'Ainu', 'a&#239;nou'),
(11, 'aka', 'Akan', 'akan'),
(12, 'akk', 'Akkadian', 'akkadien'),
(13, 'alb', 'Albanian', 'albanais'),
(14, 'ale', 'Aleut', 'al&#233;oute'),
(15, 'alg', 'Algonquian languages', 'algonquines, langues'),
(16, 'alt', 'Southern Altai', 'altai du Sud'),
(17, 'amh', 'Amharic', 'amharique'),
(18, 'ang', 'English, Old (ca.450-1100)', 'anglo-saxon (ca.450-1100)'),
(19, 'anp', 'Angika', 'angika'),
(20, 'apa', 'Apache languages', 'apache'),
(21, 'ara', 'Arabic', 'arabe'),
(22, 'arc', 'Aramaic', 'aram&#233;en'),
(23, 'arg', 'Aragonese', 'aragonais'),
(24, 'arm', 'Armenian', 'arm&#233;nien'),
(25, 'arn', 'Araucanian', 'araucan'),
(26, 'arp', 'Arapaho', 'arapaho'),
(27, 'art', 'Artificial (Other)', 'artificielles, autres langues'),
(28, 'arw', 'Arawak', 'arawak'),
(29, 'asm', 'Assamese', 'assamais'),
(30, 'ast', 'Asturian; Bable', 'asturien; bable'),
(31, 'ath', 'Athapascan languages', 'athapascanes, langues'),
(32, 'aus', 'Australian languages', 'australiennes, langues'),
(33, 'ava', 'Avaric', 'avar'),
(34, 'ave', 'Avestan', 'avestique'),
(35, 'awa', 'Awadhi', 'awadhi'),
(36, 'aym', 'Aymara', 'aymara'),
(37, 'aze', 'Azerbaijani', 'az&#233;ri'),
(38, 'bad', 'Banda', 'banda'),
(39, 'bai', 'Bamileke languages', 'bamil&#233;k&#233;s, langues'),
(40, 'bak', 'Bashkir', 'bachkir'),
(41, 'bal', 'Baluchi', 'baloutchi'),
(42, 'bam', 'Bambara', 'bambara'),
(43, 'ban', 'Balinese', 'balinais'),
(44, 'baq', 'Basque', 'basque'),
(45, 'bas', 'Basa', 'basa'),
(46, 'bat', 'Baltic (Other)', 'baltiques, autres langues'),
(47, 'bej', 'Beja', 'bedja'),
(48, 'bel', 'Belarusian', 'bi&#233;lorusse'),
(49, 'bem', 'Bemba', 'bemba'),
(50, 'ben', 'Bengali', 'bengali'),
(51, 'ber', 'Berber (Other)', 'berb&#232;res, autres langues'),
(52, 'bho', 'Bhojpuri', 'bhojpuri'),
(53, 'bih', 'Bihari', 'bihari'),
(54, 'bik', 'Bikol', 'bikol'),
(55, 'bin', 'Bini', 'bini'),
(56, 'bis', 'Bislama', 'bichlamar'),
(57, 'bla', 'Siksika', 'blackfoot'),
(58, 'bnt', 'Bantu (Other)', 'bantoues, autres langues'),
(59, 'bod', 'Tibetan', 'tib&#233;tain'),
(60, 'bos', 'Bosnian', 'bosniaque'),
(61, 'bra', 'Braj', 'braj'),
(62, 'bre', 'Breton', 'breton'),
(63, 'btk', 'Batak (Indonesia)', 'batak (Indon&#233;sie)'),
(64, 'bua', 'Buriat', 'bouriate'),
(65, 'bug', 'Buginese', 'bugi'),
(66, 'bul', 'Bulgarian', 'bulgare'),
(67, 'bur', 'Burmese', 'birman'),
(68, 'byn', 'Blin; Bilin', 'blin; bilen'),
(69, 'cad', 'Caddo', 'caddo'),
(70, 'cai', 'Central American Indian (Other)', 'indiennes d''Am&#233;rique centrale, autres langues'),
(71, 'car', 'Carib', 'caribe'),
(72, 'cat', 'Catalan; Valencian', 'catalan; valencien'),
(73, 'cau', 'Caucasian (Other)', 'caucasiennes, autres langues'),
(74, 'ceb', 'Cebuano', 'cebuano'),
(75, 'cel', 'Celtic (Other)', 'celtiques, autres langues'),
(76, 'ces', 'Czech', 'tch&#232;que'),
(77, 'cha', 'Chamorro', 'chamorro'),
(78, 'chb', 'Chibcha', 'chibcha'),
(79, 'che', 'Chechen', 'tch&#233;tch&#232;ne'),
(80, 'chg', 'Chagatai', 'djaghata&#239;'),
(81, 'chi', 'Chinese', 'chinois'),
(82, 'chk', 'Chuukese', 'chuuk'),
(83, 'chm', 'Mari', 'mari'),
(84, 'chn', 'Chinook jargon', 'chinook, jargon'),
(85, 'cho', 'Choctaw', 'choctaw'),
(86, 'chp', 'Chipewyan', 'chipewyan'),
(87, 'chr', 'Cherokee', 'cherokee'),
(88, 'chu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', 'slavon d''&#233;glise; vieux slave; slavon liturgique; vieux bulgare'),
(89, 'chv', 'Chuvash', 'tchouvache'),
(90, 'chy', 'Cheyenne', 'cheyenne'),
(91, 'cmc', 'Chamic languages', 'chames, langues'),
(92, 'cop', 'Coptic', 'copte'),
(93, 'cor', 'Cornish', 'cornique'),
(94, 'cos', 'Corsican', 'corse'),
(95, 'cpe', 'Creoles and pidgins, English based (Other)', 'cr&#233;oles et pidgins anglais, autres'),
(96, 'cpf', 'Creoles and pidgins, French-based (Other)', 'cr&#233;oles et pidgins fran&#231;ais, autres'),
(97, 'cpp', 'Creoles and pidgins, Portuguese-based (Other)', 'cr&#233;oles et pidgins portugais, autres'),
(98, 'cre', 'Cree', 'cree'),
(99, 'crh', 'Crimean Tatar; Crimean Turkish', 'tatar de Crim&#233;'),
(100, 'crp', 'Creoles and pidgins (Other)', 'cr&#233;oles et pidgins divers'),
(101, 'csb', 'Kashubian', 'kachoube'),
(102, 'cus', 'Cushitic (Other)', 'couchitiques, autres langues'),
(103, 'cym', 'Welsh', 'gallois'),
(104, 'cze', 'Czech', 'tch&#232;que'),
(105, 'dak', 'Dakota', 'dakota'),
(106, 'dan', 'Danish', 'danois'),
(107, 'dar', 'Dargwa', 'dargwa'),
(108, 'day', 'Dayak', 'dayak'),
(109, 'del', 'Delaware', 'delaware'),
(110, 'den', 'Slave (Athapascan)', 'esclave (athapascan)'),
(111, 'deu', 'German', 'allemand'),
(112, 'dgr', 'Dogrib', 'dogrib'),
(113, 'din', 'Dinka', 'dinka'),
(114, 'div', 'Divehi; Dhivehi; Maldivian', 'maldivien'),
(115, 'doi', 'Dogri', 'dogri'),
(116, 'dra', 'Dravidian (Other)', 'dravidiennes, autres langues'),
(117, 'dsb', 'Lower Sorbian', 'bas-sorabe'),
(118, 'dua', 'Duala', 'douala'),
(119, 'dum', 'Dutch, Middle (ca.1050-1350)', 'n&#233;erlandais moyen (ca. 1050-1350)'),
(120, 'dut', 'Dutch; Flemish', 'n&#233;erlandais; flamand'),
(121, 'dyu', 'Dyula', 'dioula'),
(122, 'dzo', 'Dzongkha', 'dzongkha'),
(123, 'efi', 'Efik', 'efik'),
(124, 'egy', 'Egyptian (Ancient)', '&#233;gyptien'),
(125, 'eka', 'Ekajuk', 'ekajuk'),
(126, 'ell', 'Greek, Modern (1453-)', 'grec moderne (apr&#232;s 1453)'),
(127, 'elx', 'Elamite', '&#233;lamite'),
(128, 'eng', 'English', 'anglais'),
(129, 'enm', 'English, Middle (1100-1500)', 'anglais moyen (1100-1500)'),
(130, 'epo', 'Esperanto', 'esp&#233;ranto'),
(131, 'est', 'Estonian', 'estonien'),
(132, 'eus', 'Basque', 'basque'),
(133, 'ewe', 'Ewe', '&#233;w&#233;'),
(134, 'ewo', 'Ewondo', '&#233;wondo'),
(135, 'fan', 'Fang', 'fang'),
(136, 'fao', 'Faroese', 'f&#233;ro&#239;en'),
(137, 'fas', 'Persian', 'persan'),
(138, 'fat', 'Fanti', 'fanti'),
(139, 'fij', 'Fijian', 'fidjien'),
(140, 'fil', 'Filipino; Pilipino', 'filipino; pilipino'),
(141, 'fin', 'Finnish', 'finnois'),
(142, 'fiu', 'Finno-Ugrian (Other)', 'finno-ougriennes, autres langues'),
(143, 'fon', 'Fon', 'fon'),
(144, 'fra', 'French', 'fran&#231;ais'),
(145, 'fre', 'French', 'fran&#231;ais'),
(146, 'frm', 'French, Middle (ca.1400-1600)', 'fran&#231;ais moyen (1400-1600)'),
(147, 'fro', 'French, Old (842-ca.1400)', 'fran&#231;ais ancien (842-ca.1400)'),
(148, 'frr', 'Northern Frisian', 'frison septentrional'),
(149, 'frs', 'Eastern Frisian', 'frison oriental'),
(150, 'fry', 'Western Frisian', 'frison occidental'),
(151, 'ful', 'Fulah', 'peul'),
(152, 'fur', 'Friulian', 'frioulan'),
(153, 'gaa', 'Ga', 'ga'),
(154, 'gay', 'Gayo', 'gayo'),
(155, 'gba', 'Gbaya', 'gbaya'),
(156, 'gem', 'Germanic (Other)', 'germaniques, autres langues'),
(157, 'geo', 'Georgian', 'g&#233;orgien'),
(158, 'ger', 'German', 'allemand'),
(159, 'gez', 'Geez', 'gu&#232;ze'),
(160, 'gil', 'Gilbertese', 'kiribati'),
(161, 'gla', 'Gaelic; Scottish Gaelic', 'ga&#233;lique; ga&#233;lique &#233;cossais'),
(162, 'gle', 'Irish', 'irlandais'),
(163, 'glg', 'Galician', 'galicien'),
(164, 'glv', 'Manx 	manx; mannois', ''),
(165, 'gmh', 'German, Middle High (ca.1050-1500)', 'allemand, moyen haut (ca. 1050-1500)'),
(166, 'goh', 'German, Old High (ca.750-1050)', 'allemand, vieux haut (ca. 750-1050)'),
(167, 'gon', 'Gondi', 'gond'),
(168, 'gor', 'Gorontalo', 'gorontalo'),
(169, 'got', 'Gothic', 'gothique'),
(170, 'grb', 'Grebo', 'grebo'),
(171, 'grc', 'Greek, Ancient (to 1453)', 'grec ancien (jusqu''&#224; 1453)'),
(172, 'gre', 'Greek, Modern (1453-)', 'grec moderne (apr&#232;s 1453)'),
(173, 'grn', 'Guarani', 'guarani'),
(174, 'gsw', 'Alemani; Swiss German', 'al&#233;manique'),
(175, 'guj', 'Gujarati', 'goudjrati'),
(176, 'gwi', 'Gwich&#180;in', 'gwich&#180;in'),
(177, 'hai', 'Haida', 'haida'),
(178, 'hat', 'Haitian; Haitian Creole', 'ha&#239;tien; cr&#233;ole ha&#239;tien'),
(179, 'hau', 'Hausa', 'haoussa'),
(180, 'haw', 'Hawaiian', 'hawa&#239;en'),
(181, 'heb', 'Hebrew', 'h&#233;breu'),
(182, 'her', 'Herero', 'herero'),
(183, 'hil', 'Hiligaynon', 'hiligaynon'),
(184, 'him', 'Himachali', 'himachali'),
(185, 'hin', 'Hindi', 'hindi'),
(186, 'hit', 'Hittite', 'hittite'),
(187, 'hmn', 'Hmong', 'hmong'),
(188, 'hmo', 'Hiri Motu', 'hiri motu'),
(189, 'hrv', 'Croatian', 'croate'),
(190, 'hsb', 'Upper Sorbian', 'haut-sorabe'),
(191, 'hun', 'Hungarian', 'hongrois'),
(192, 'hup', 'Hupa', 'hupa'),
(193, 'hye', 'Armenian', 'arm&#233;nien'),
(194, 'iba', 'Iban', 'iban'),
(195, 'ibo', 'Igbo', 'igbo'),
(196, 'ice', 'Icelandic', 'islandais'),
(197, 'ido', 'Ido', 'ido'),
(198, 'iii', 'Sichuan Yi', 'yi de Sichuan'),
(199, 'ijo', 'Ijo', 'ijo'),
(200, 'iku', 'Inuktitut', 'inuktitut'),
(201, 'ile', 'Interlingue', 'interlingue'),
(202, 'ilo', 'Iloko', 'ilocano'),
(203, 'ina', 'Interlingua (International Auxiliary Language Association)', 'interlingua (langue auxiliaire internationale)'),
(204, 'inc', 'Indic (Other)', 'indo-aryennes, autres langues'),
(205, 'ind', 'Indonesian', 'indon&#233;sien'),
(206, 'ine', 'Indo-European (Other)', 'indo-europ&#233;ennes, autres langues'),
(207, 'inh', 'Ingush 	ingouche', ''),
(208, 'ipk', 'Inupiaq', 'inupiaq'),
(209, 'ira', 'Iranian (Other)', 'iraniennes, autres langues'),
(210, 'iro', 'Iroquoian languages', 'iroquoises, langues (famille)'),
(211, 'isl', 'Icelandic', 'islandais'),
(212, 'ita', 'Italian', 'italien'),
(213, 'jav', 'Javanese', 'javanais'),
(214, 'jbo', 'Lojban', 'lojban'),
(215, 'jpn', 'Japanese', 'japonais'),
(216, 'jpr', 'Judeo-Persian', 'jud&#233;o-persan'),
(217, 'jrb', 'Judeo-Arabic', 'jud&#233;o-arabe'),
(218, 'kaa', 'Kara-Kalpak', 'karakalpak'),
(219, 'kab', 'Kabyle', 'kabyle'),
(220, 'kac', 'Kachin', 'kachin'),
(221, 'kal', 'Kalaallisut; Greenlandic', 'groenlandais'),
(222, 'kam', 'Kamba', 'kamba'),
(223, 'kan', 'Kannada', 'kannada'),
(224, 'kar', 'Karen', 'karen'),
(225, 'kas', 'Kashmiri', 'kashmiri'),
(226, 'kat', 'Georgian', 'g&#233;orgien'),
(227, 'kau', 'Kanuri', 'kanouri'),
(228, 'kaw', 'Kawi', 'kawi'),
(229, 'kaz', 'Kazakh', 'kazakh'),
(230, 'kbd', 'Kabardian', 'kabardien'),
(231, 'kha', 'Khasi', 'khasi'),
(232, 'khi', 'Khoisan (Other)', 'khoisan, autres langues'),
(233, 'khm', 'Khmer', 'khmer'),
(234, 'kho', 'Khotanese', 'khotanais'),
(235, 'kik', 'Kikuyu; Gikuyu', 'kikuyu'),
(236, 'kin', 'Kinyarwanda', 'rwanda'),
(237, 'kir', 'Kirghiz', 'kirghize'),
(238, 'kmb', 'Kimbundu', 'kimbundu'),
(239, 'kok', 'Konkani', 'konkani'),
(240, 'kom', 'Komi', 'kom'),
(241, 'kon', 'Kongo', 'kongo'),
(242, 'kor', 'Korean', 'cor&#233;en'),
(243, 'kos', 'Kosraean', 'kosrae'),
(244, 'kpe', 'Kpelle', 'kpell&#233;'),
(245, 'krc', 'Karachay-Balkar', 'karatchai balkar'),
(246, 'krl', 'Karelian', 'car&#233;lien'),
(247, 'kro', 'Kru', 'krou'),
(248, 'kru', 'Kurukh', 'kurukh'),
(249, 'kua', 'Kuanyama; Kwanyama', 'kuanyama; kwanyama'),
(250, 'kum', 'Kumyk', 'koumyk'),
(251, 'kur', 'Kurdish', 'kurde'),
(252, 'kut', 'Kutenai', 'kutenai'),
(253, 'lad', 'Ladino', 'jud&#233;o-espagnol'),
(254, 'lah', 'Lahnda', 'lahnda'),
(255, 'lam', 'Lamba', 'lamba'),
(256, 'lao', 'Lao', 'lao'),
(257, 'lat', 'Latin', 'latin'),
(258, 'lav', 'Latvian', 'letton'),
(259, 'lez', 'Lezghian', 'lezghien'),
(260, 'lim', 'Limburgan; Limburger; Limburgish', 'limbourgeois'),
(261, 'lin', 'Lingala', 'lingala'),
(262, 'lit', 'Lithuanian', 'lituanien'),
(263, 'lol', 'Mongo', 'mongo'),
(264, 'loz', 'Lozi', 'lozi'),
(265, 'ltz', 'Luxembourgish; Letzeburgesch', 'luxembourgeois'),
(266, 'lua', 'Luba-Lulua', 'luba-lulua'),
(267, 'lub', 'Luba-Katanga', 'luba-katanga'),
(268, 'lug', 'Ganda', 'ganda'),
(269, 'lui', 'Luiseno', 'luiseno'),
(270, 'lun', 'Lunda', 'lunda'),
(271, 'luo', 'Luo (Kenya and Tanzania)', 'luo (Kenya et Tanzanie)'),
(272, 'lus', 'Lushai', 'lushai'),
(273, 'mac', 'Macedonian', 'mac&#233;donien'),
(274, 'mad', 'Madurese', 'madourais'),
(275, 'mag', 'Magahi', 'magahi'),
(276, 'mah', 'Marshallese', 'marshall'),
(277, 'mai', 'Maithili', 'maithili'),
(278, 'mak', 'Makasar', 'makassar'),
(279, 'mal', 'Malayalam', 'malayalam'),
(280, 'man', 'Mandingo', 'mandingue'),
(281, 'mao', 'Maori', 'maori'),
(282, 'map', 'Austronesian (Other)', 'malayo-polyn&#233;siennes, autres langues'),
(283, 'mar', 'Marathi', 'marathe'),
(284, 'mas', 'Masai', 'massa&#239;'),
(285, 'may', 'Malay', 'malais'),
(286, 'mdf', 'Moksha', 'moksa'),
(287, 'mdr', 'Mandar', 'mandar'),
(288, 'men', 'Mende', 'mend&#233;'),
(289, 'mga', 'Irish, Middle (900-1200)', 'irlandais moyen (900-1200)'),
(290, 'mic', 'Mi''kmaq; Micmac', 'mi''kmaq; micmac'),
(291, 'min', 'Minangkabau', 'minangkabau'),
(292, 'mis', 'Miscellaneous languages', 'diverses, langues'),
(293, 'mkd', 'Macedonian', 'mac&#233;donien'),
(294, 'mkh', 'Mon-Khmer (Other)', 'm&#244;n-khmer, autres langues'),
(295, 'mlg', 'Malagasy', 'malgache'),
(296, 'mlt', 'Maltese', 'maltais'),
(297, 'mnc', 'Manchu', 'mandchou'),
(298, 'mni', 'Manipuri', 'manipuri'),
(299, 'mno', 'Manobo languages', 'manobo, langues'),
(300, 'moh', 'Mohawk', 'mohawk'),
(301, 'mol', 'Moldavian', 'moldave'),
(302, 'mon', 'Mongolian', 'mongol'),
(303, 'mos', 'Mossi', 'mor&#233;'),
(304, 'mri', 'Maori', 'maori'),
(305, 'msa', 'Malay', 'malais'),
(306, 'mul', 'Multiple languages', 'multilingue'),
(307, 'mun', 'Munda languages', 'mounda, langues'),
(308, 'mus', 'Creek', 'muskogee'),
(309, 'mwl', 'Mirandese', 'mirandais'),
(310, 'mwr', 'Marwari', 'marvari'),
(311, 'mya', 'Burmese', 'birman'),
(312, 'myn', 'Mayan languages', 'maya, langues'),
(313, 'myv', 'Erzya', 'erza'),
(314, 'nah', 'Nahuatl', 'nahuatl'),
(315, 'nai', 'North American Indian', 'indiennes d''Am&#233;rique du Nord, autres langues'),
(316, 'nap', 'Neapolitan', 'napolitain'),
(317, 'nau', 'Nauru', 'nauruan'),
(318, 'nav', 'Navajo; Navaho', 'navaho'),
(319, 'nbl', 'Ndebele, South; South Ndebele', 'nd&#233;b&#233;l&#233; du Sud'),
(320, 'nde', 'Ndebele, North; North Ndebele', 'nd&#233;b&#233;l&#233; du Nord'),
(321, 'ndo', 'Ndonga', 'ndonga'),
(322, 'nds', 'Low German; Low Saxon; German, Low; Saxon, Low', 'bas allemand; bas saxon; allemand, bas; saxon, bas'),
(323, 'nep', 'Nepali', 'n&#233;palais'),
(324, 'new', 'Nepal Bhasa; Newari', 'nepal bhasa; newari'),
(325, 'nia', 'Nias', 'nias'),
(326, 'nic', 'Niger-Kordofanian (Other)', 'nig&#233;ro-congolaises, autres langues'),
(327, 'niu', 'Niuean', 'niu&#233;'),
(328, 'nld', 'Dutch; Flemish', 'n&#233;erlandais; flamand'),
(329, 'nno', 'Norwegian Nynorsk; Nynorsk, Norwegian', 'norv&#233;gien nynorsk; nynorsk, norv&#233;gien'),
(330, 'nob', 'Bokm&#229;l, Norwegian; Norwegian Bokm&#229;l', 'norv&#233;gien bokm&#229;l'),
(331, 'nog', 'Nogai', 'noga&#239;; nogay'),
(332, 'non', 'Norse, Old', 'norrois, vieux'),
(333, 'nor', 'Norwegian', 'norv&#233;gien'),
(334, 'nqo', 'N''Ko', 'n''ko'),
(335, 'nso', 'Pedi; Sepedi; Northern Sotho', 'pedi; sepedi; sotho du Nord'),
(336, 'nub', 'Nubian languages', 'nubiennes, langues'),
(337, 'nwc', 'Classical Newari; Old Newari; Classical Nepal Bhasa', 'newari classique'),
(338, 'nya', 'Chichewa; Chewa; Nyanja 	chichewa; chewa; nyanja', ''),
(339, 'nym', 'Nyamwezi', 'nyamwezi'),
(340, 'nyn', 'Nyankole', 'nyankol&#233;'),
(341, 'nyo', 'Nyoro', 'nyoro'),
(342, 'nzi', 'Nzima', 'nzema'),
(343, 'oci', 'Occitan (post 1500); Proven&#231;al', 'occitan (apr&#232;s 1500); proven&#231;al'),
(344, 'oji', 'Ojibwa', 'ojibwa'),
(345, 'ori', 'Oriya', 'oriya'),
(346, 'orm', 'Oromo', 'galla'),
(347, 'osa', 'Osage', 'osage'),
(348, 'oss', 'Ossetian; Ossetic', 'oss&#232;te'),
(349, 'ota', 'Turkish, Ottoman (1500-1928)', 'turc ottoman (1500-1928)'),
(350, 'oto', 'Otomian languages', 'otomangue, langues'),
(351, 'paa', 'Papuan (Other)', 'papoues, autres langues'),
(352, 'pag', 'Pangasinan', 'pangasinan'),
(353, 'pal', 'Pahlavi', 'pahlavi'),
(354, 'pam', 'Pampanga', 'pampangan'),
(355, 'pan', 'Panjabi; Punjabi', 'pendjabi'),
(356, 'pap', 'Papiamento', 'papiamento'),
(357, 'pau', 'Palauan', 'palau'),
(358, 'peo', 'Persian, Old (ca.600-400 B.C.)', 'perse, vieux (ca. 600-400 av. J.-C.)'),
(359, 'per', 'Persian', 'persan'),
(360, 'phi', 'Philippine (Other)', 'philippines, autres langues'),
(361, 'phn', 'Phoenician', 'ph&#233;nicien'),
(362, 'pli', 'Pali', 'pali'),
(363, 'pol', 'Polish', 'polonais'),
(364, 'pon', 'Pohnpeian', 'pohnpei'),
(365, 'por', 'Portuguese', 'portugais'),
(366, 'pra', 'Prakrit languages', 'pr&#226;krit'),
(367, 'pro', 'Proven&#231;al, Old (to 1500)', 'proven&#231;al ancien (jusqu''&#224; 1500)'),
(368, 'pus', 'Pushto', 'pachto'),
(369, 'que', 'Quechua', 'quechua'),
(370, 'raj', 'Rajasthani', 'rajasthani'),
(371, 'rap', 'Rapanui', 'rapanui'),
(372, 'rar', 'Rarotongan', 'rarotonga'),
(373, 'roa', 'Romance (Other)', 'romanes, autres langues'),
(374, 'roh', 'Raeto-Romance', 'rh&#233;to-roman'),
(375, 'rom', 'Romany', 'tsigane'),
(376, 'ron', 'Romanian', 'roumain'),
(377, 'rum', 'Romanian', 'roumain'),
(378, 'run', 'Rundi', 'rundi'),
(379, 'rup', 'Aromanian; Arumanian; Macedo-Romanian', 'aroumain; mac&#233;do-roumain'),
(380, 'rus', 'Russian', 'russe'),
(381, 'sad', 'Sandawe', 'sandawe'),
(382, 'sag', 'Sango', 'sango'),
(383, 'sah', 'Yakut', 'iakoute'),
(384, 'sai', 'South American Indian (Other)', 'indiennes d''Am&#233;rique du Sud, autres langues'),
(385, 'sal', 'Salishan languages', 'salish, langues'),
(386, 'sam', 'Samaritan Aramaic', 'samaritain'),
(387, 'san', 'Sanskrit', 'sanskrit'),
(388, 'sas', 'Sasak', 'sasak'),
(389, 'sat', 'Santali', 'santal'),
(390, 'scc', 'Serbian', 'serbe'),
(391, 'scn', 'Sicilian', 'sicilien'),
(392, 'sco', 'Scots', '&#233;cossais'),
(393, 'scr', 'Croatian', 'croate'),
(394, 'sel', 'Selkup', 'selkoupe'),
(395, 'sem', 'Semitic (Other)', 's&#233;mitiques, autres langues'),
(396, 'sga', 'Irish, Old (to 900)', 'irlandais ancien (jusqu''&#224; 900)'),
(397, 'sgn', 'Sign Languages', 'langues des signes'),
(398, 'shn', 'Shan', 'chan'),
(399, 'sid', 'Sidamo', 'sidamo'),
(400, 'sin', 'Sinhala; Sinhalese', 'singhalais'),
(401, 'sio', 'Siouan languages', 'sioux, langues'),
(402, 'sit', 'Sino-Tibetan (Other)', 'sino-tib&#233;taines, autres langues'),
(403, 'sla', 'Slavic (Other)', 'slaves, autres langues'),
(404, 'slk', 'Slovak', 'slovaque'),
(405, 'slo', 'Slovak', 'slovaque'),
(406, 'slv', 'Slovenian', 'slov&#232;ne'),
(407, 'sma', 'Southern Sami', 'sami du Sud'),
(408, 'sme', 'Northern Sami', 'sami du Nord'),
(409, 'smi', 'Sami languages (Other)', 'sami, autres langues'),
(410, 'smj', 'Lule Sami', 'sami de Lule'),
(411, 'smn', 'Inari Sami', 'sami d''Inari'),
(412, 'smo', 'Samoan', 'samoan'),
(413, 'sms', 'Skolt Sami', 'sami skolt'),
(414, 'sna', 'Shona', 'shona'),
(415, 'snd', 'Sindhi', 'sindhi'),
(416, 'snk', 'Soninke', 'sonink&#233;'),
(417, 'sog', 'Sogdian', 'sogdien'),
(418, 'som', 'Somali', 'somali'),
(419, 'son', 'Songhai', 'songhai'),
(420, 'sot', 'Sotho, Southern', 'sotho du Sud'),
(421, 'spa', 'Spanish; Castilian', 'espagnol; castillan'),
(422, 'sqi', 'Albanian', 'albanais'),
(423, 'srd', 'Sardinian', 'sarde'),
(424, 'srn', 'Sranan Togo', 'sranan togo'),
(425, 'srp', 'Serbian', 'serbe'),
(426, 'srr', 'Serer', 's&#233;r&#232;re'),
(427, 'ssa', 'Nilo-Saharan (Other)', 'nilo-sahariennes, autres langues'),
(428, 'ssw', 'Swati', 'swati'),
(429, 'suk', 'Sukuma', 'sukuma'),
(430, 'sun', 'Sundanese', 'soundanais'),
(431, 'sus', 'Susu', 'soussou'),
(432, 'sux', 'Sumerian', 'sum&#233;rien'),
(433, 'swa', 'Swahili', 'swahili'),
(434, 'swe', 'Swedish', 'su&#233;dois'),
(435, 'syr', 'Syriac', 'syriaque'),
(436, 'tah', 'Tahitian', 'tahitien'),
(437, 'tai', 'Tai (Other)', 'tha&#239;es, autres langues'),
(438, 'tam', 'Tamil', 'tamoul'),
(439, 'tat', 'Tatar', 'tatar'),
(440, 'tel', 'Telugu', 't&#233;lougou'),
(441, 'tem', 'Timne', 'temne'),
(442, 'ter', 'Tereno', 'tereno'),
(443, 'tet', 'Tetum', 'tetum'),
(444, 'tgk', 'Tajik', 'tadjik'),
(445, 'tgl', 'Tagalog', 'tagalog'),
(446, 'tha', 'Thai', 'tha&#239;'),
(447, 'tib', 'Tibetan', 'tib&#233;tain'),
(448, 'tig', 'Tigre', 'tigr&#233;'),
(449, 'tir', 'Tigrinya', 'tigrigna'),
(450, 'tiv', 'Tiv', 'tiv'),
(451, 'tkl', 'Tokelau', 'tokelau'),
(452, 'tlh', 'Klingon; tlhIngan-Hol', 'klingon'),
(453, 'tli', 'Tlingit', 'tlingit'),
(454, 'tmh', 'Tamashek', 'tamacheq'),
(455, 'tog', 'Tonga (Nyasa)', 'tonga (Nyasa)'),
(456, 'ton', 'Tonga (Tonga Islands)', 'tongan (&#206;les Tonga)'),
(457, 'tpi', 'Tok Pisin', 'tok pisin'),
(458, 'tsi', 'Tsimshian', 'tsimshian'),
(459, 'tsn', 'Tswana', 'tswana'),
(460, 'tso', 'Tsonga', 'tsonga'),
(461, 'tuk', 'Turkmen', 'turkm&#232;ne'),
(462, 'tum', 'Tumbuka', 'tumbuka'),
(463, 'tup', 'Tupi languages', 'tupi, langues'),
(464, 'tur', 'Turkish', 'turc'),
(465, 'tut', 'Altaic (Other)', 'alta&#239;ques, autres langues'),
(466, 'tvl', 'Tuvalu', 'tuvalu'),
(467, 'twi', 'Twi', 'twi'),
(468, 'tyv', 'Tuvinian', 'touva'),
(469, 'udm', 'Udmurt', 'oudmourte'),
(470, 'uga', 'Ugaritic', 'ougaritique'),
(471, 'uig', 'Uighur; Uyghur', 'ou&#239;gour'),
(472, 'ukr', 'Ukrainian', 'ukrainien'),
(473, 'umb', 'Umbundu', 'umbundu'),
(474, 'und', 'Undetermined', 'ind&#233;termin&#233;e'),
(475, 'urd', 'Urdu', 'ourdou'),
(476, 'uzb', 'Uzbek', 'ouszbek'),
(477, 'vai', 'Vai', 'va&#239;'),
(478, 'ven', 'Venda', 'venda'),
(479, 'vie', 'Vietnamese', 'vietnamien'),
(480, 'vol', 'Volap&#252;k', 'volap&#252;k'),
(481, 'vot', 'Votic', 'vote'),
(482, 'wak', 'Wakashan languages', 'wakashennes, langues'),
(483, 'wal', 'Walamo', 'walamo'),
(484, 'war', 'Waray', 'waray'),
(485, 'was', 'Washo', 'washo'),
(486, 'wel', 'Welsh', 'gallois'),
(487, 'wen', 'Sorbian languages', 'sorabes, langues'),
(488, 'wln', 'Walloon', 'wallon'),
(489, 'wol', 'Wolof', 'wolof'),
(490, 'xal', 'Kalmyk; Oirat', 'kalmouk; o&#239;rat'),
(491, 'xho', 'Xhosa', 'xhosa'),
(492, 'yao', 'Yao', 'yao'),
(493, 'yap', 'Yapese', 'yapois'),
(494, 'yid', 'Yiddish', 'yiddish'),
(495, 'yor', 'Yoruba', 'yoruba'),
(496, 'ypk', 'Yupik languages', 'yupik, langues'),
(497, 'zap', 'Zapotec', 'zapot&#232;que'),
(498, 'zen', 'Zenaga', 'zenaga'),
(499, 'zha', 'Zhuang; Chuang', 'zhuang; chuang'),
(500, 'zho', 'Chinese', 'chinois'),
(501, 'znd', 'Zande', 'zand&#233;'),
(502, 'zul', 'Zulu', 'zoulou'),
(503, 'zun', 'Zuni', 'zuni'),
(504, 'zxx', 'No linguistic content', 'pas de contenu linguistique'),
(505, 'zza', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki', 'zaza; dimili; dimli; kirdki; kirmanjki; zazaki');
