

INSERT INTO `orbicon_sys_iso_639_1_codes` (`id`, `iso_code`, `en`, `fr`) VALUES (1, 'aa', 'Afar', 'afar'),
(2, 'ab', 'Abkhazian', 'abkhaze'),
(3, 'ad', 'Adangme', 'adangme'),
(4, 'ae', 'Avestan', 'avestique'),
(5, 'af', 'Afrikaans', 'afrikaans'),
(6, 'ak', 'Akan', 'akan'),
(7, 'am', 'Amharic', 'amharique'),
(8, 'an', 'Aragonese', 'aragonais'),
(9, 'ar', 'Arabic', 'arabe'),
(10, 'as', 'Assamese', 'assamais'),
(11, 'av', 'Avaric', 'avar'),
(12, 'ay', 'Aymara', 'aymara'),
(13, 'az', 'Azerbaijani', 'az&#233;ri'),
(14, 'ba', 'Bashkir', 'bachkir'),
(15, 'be', 'Belarusian', 'bi&#233;lorusse'),
(16, 'bg', 'Bulgarian', 'bulgare'),
(17, 'bh', 'Bihari', 'bihari'),
(18, 'bi', 'Bislama', 'bichlamar'),
(19, 'bm', 'Bambara', 'bambara'),
(20, 'bn', 'Bengali', 'bengali'),
(21, 'bo', 'Tibetan', 'tib&#233;tain'),
(22, 'br', 'Breton', 'breton'),
(23, 'bs', 'Bosnian', 'bosniaque'),
(24, 'ca', 'Catalan; Valencian', 'catalan; valencien'),
(25, 'ce', 'Chechen', 'tch&#233;tch&#232;ne'),
(26, 'ch', 'Chamorro', 'chamorro'),
(27, 'co', 'Corsican', 'corse'),
(28, 'cr', 'Cree', 'cree'),
(29, 'cs', 'Czech', 'tch&#232;que'),
(30, 'cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', 'slavon d''&#233;glise; vieux slave; slavon liturgique; vieux bulgare'),
(31, 'cv', 'Chuvash', 'tchouvache'),
(32, 'cy', 'Welsh', 'gallois'),
(33, 'da', 'Danish', 'danois'),
(34, 'de', 'German', 'allemand'),
(35, 'dv', 'Divehi; Dhivehi; Maldivian', 'maldivien'),
(36, 'dz', 'Dzongkha', 'dzongkha'),
(37, 'ee', 'Ewe', '&#233;w&#233;'),
(38, 'el', 'Greek, Modern (1453-)', 'grec moderne (apr&#232;s 1453)'),
(39, 'en', 'English', 'anglais'),
(40, 'eo', 'Esperanto', 'esp&#233;ranto'),
(41, 'es', 'Spanish; Castilian', 'espagnol; castillan'),
(42, 'et', 'Estonian', 'estonien'),
(43, 'eu', 'Basque', 'basque'),
(44, 'fa', 'Persian', 'persan'),
(45, 'ff', 'Fulah', 'peul'),
(46, 'fi', 'Finnish', 'finnois'),
(47, 'fj', 'Fijian', 'fidjien'),
(48, 'fo', 'Faroese', 'f&#233;ro&#239;en'),
(49, 'fr', 'French', 'fran&#231;ais'),
(50, 'fy', 'Western Frisian', 'frison occidental'),
(51, 'ga', 'Irish', 'irlandais'),
(52, 'gd', 'Gaelic; Scottish Gaelic', 'ga&#233;lique; ga&#233;lique &#233;cossais'),
(53, 'gl', 'Galician', 'galicien'),
(54, 'gn', 'Guarani', 'guarani'),
(55, 'gu', 'Gujarati', 'goudjrati'),
(56, 'gv', 'Manx', 'manx; mannois'),
(57, 'ha', 'Hausa', 'haoussa'),
(58, 'he', 'Hebrew', 'h&#233;breu'),
(59, 'hi', 'Hindi', 'hindi'),
(60, 'ho', 'Hiri Motu', 'hiri motu'),
(61, 'hr', 'Croatian', 'croate'),
(62, 'ht', 'Haitian; Haitian Creole', 'ha&#239;tien; cr&#233;ole ha&#239;tien'),
(63, 'hu', 'Hungarian', 'hongrois'),
(64, 'hy', 'Armenian', 'arm&#233;nien'),
(65, 'hz', 'Herero', 'herero'),
(66, 'ia', 'Interlingua (International Auxiliary Language Association)', 'interlingua (langue auxiliaire internationale)'),
(67, 'id', 'Indonesian', 'indon&#233;sien'),
(68, 'ie', 'Interlingue', 'interlingue'),
(69, 'ig', 'Igbo', 'igbo'),
(70, 'ii', 'Sichuan Yi', 'yi de Sichuan'),
(71, 'ik', 'Inupiaq', 'inupiaq'),
(72, 'io', 'Ido', 'ido'),
(73, 'is', 'Icelandic', 'islandais'),
(74, 'it', 'Italian', 'italien'),
(75, 'iu', 'Inuktitut', 'inuktitut'),
(76, 'ja', 'Japanese', 'japonais'),
(77, 'jv', 'Javanese', 'javanais'),
(78, 'ka', 'Georgian', 'g&#233;orgien'),
(79, 'kg', 'Kongo', 'kongo'),
(80, 'ki', 'Kikuyu; Gikuyu', 'kikuyu'),
(81, 'kj', 'Kuanyama; Kwanyama', 'kuanyama; kwanyama'),
(82, 'kk', 'Kazakh', 'kazakh'),
(83, 'kl', 'Kalaallisut; Greenlandic', 'groenlandais'),
(84, 'km', 'Khmer', 'khmer'),
(85, 'kn', 'Kannada', 'kannada'),
(86, 'ko', 'Korean', 'cor&#233;en'),
(87, 'kr', 'Kanuri', 'kanouri'),
(88, 'ks', 'Kashmiri', 'kashmiri'),
(89, 'ku', 'Kurdish', 'kurde'),
(90, 'kv', 'Komi', 'kom'),
(91, 'kw', 'Cornish', 'cornique'),
(92, 'ky', 'Kirghiz', 'kirghize'),
(93, 'la', 'Latin', 'latin'),
(94, 'lb', 'Luxembourgish; Letzeburgesch', 'luxembourgeois'),
(95, 'lg', 'Ganda', 'ganda'),
(96, 'li', 'Limburgan; Limburger; Limburgish', 'limbourgeois'),
(97, 'ln', 'Lingala', 'lingala'),
(98, 'lo', 'Lao', 'lao'),
(99, 'lt', 'Lithuanian', 'lituanien'),
(100, 'lu', 'Luba-Katanga', 'luba-katanga'),
(101, 'lv', 'Latvian', 'letton'),
(102, 'mg', 'Malagasy', 'malgache'),
(103, 'mh', 'Marshallese', 'marshall'),
(104, 'mi', 'Maori', 'maori'),
(105, 'mk', 'Macedonian', 'mac&#233;donien'),
(106, 'ml', 'Malayalam', 'malayalam'),
(107, 'mn', 'Mongolian', 'mongol'),
(108, 'mo', 'Moldavian', 'moldave'),
(109, 'mr', 'Marathi', 'marathe'),
(110, 'ms', 'Malay', 'malais'),
(111, 'mt', 'Maltese', 'maltais'),
(112, 'my', 'Burmese', 'birman'),
(113, 'na', 'Nauru', 'nauruan'),
(114, 'nb', 'Bokm&#229;l, Norwegian; Norwegian Bokm&#229;l', 'norv&#233;gien bokm&#229;l'),
(115, 'nd', 'Ndebele, North; North Ndebele', 'nd&#233;b&#233;l&#233; du Nord'),
(116, 'ne', 'Nepali', 'n&#233;palais'),
(117, 'ng', 'Ndonga', 'ndonga'),
(118, 'nl', 'Dutch; Flemish', 'n&#233;erlandais; flamand'),
(119, 'nn', 'Norwegian Nynorsk; Nynorsk, Norwegian', 'norv&#233;gien nynorsk; nynorsk, norv&#233;gien'),
(120, 'no', 'Norwegian', 'norv&#233;gien'),
(121, 'nr', 'Ndebele, South; South Ndebele', 'nd&#233;b&#233;l&#233; du Sud'),
(122, 'nv', 'Navajo; Navaho', 'navaho'),
(123, 'ny', 'Chichewa; Chewa; Nyanja', 'chichewa; chewa; nyanja'),
(124, 'oc', 'Occitan (post 1500); Proven&#231;al', 'occitan (apr&#232;s 1500); proven&#231;al'),
(125, 'oj', 'Ojibwa', 'ojibwa'),
(126, 'om', 'Oromo', 'galla'),
(127, 'or', 'Oriya', 'oriya'),
(128, 'os', 'Ossetian; Ossetic', 'oss&#232;te'),
(129, 'pa', 'Panjabi; Punjabi', 'pendjabi'),
(130, 'pi', 'Pali', 'pali'),
(131, 'pl', 'Polish', 'polonais'),
(132, 'ps', 'Pushto', 'pachto'),
(133, 'pt', 'Portuguese', 'portugais'),
(134, 'qu', 'Quechua', 'quechua'),
(135, 'rm', 'Raeto-Romance', 'rh&#233;to-roman'),
(136, 'rn', 'Rundi', 'rundi'),
(137, 'ro', 'Romanian', 'roumain'),
(138, 'ru', 'Russian', 'russe'),
(139, 'rw', 'Kinyarwanda', 'rwanda'),
(140, 'sa', 'Sanskrit', 'sanskrit'),
(141, 'sc', 'Sardinian', 'sarde'),
(142, 'sd', 'Sindhi', 'sindhi'),
(143, 'se', 'Northern Sami', 'sami du Nord'),
(144, 'sg', 'Sango', 'sango'),
(145, 'si', 'Sinhala; Sinhalese', 'singhalais'),
(146, 'sk', 'Slovak', 'slovaque'),
(147, 'sl', 'Slovenian', 'slov&#232;ne'),
(148, 'sm', 'Samoan', 'samoan'),
(149, 'sn', 'Shona', 'shona'),
(150, 'so', 'Somali', 'somali'),
(151, 'sq', 'Albanian', 'albanais'),
(152, 'sr', 'Serbian', 'serbe'),
(153, 'ss', 'Swati', 'swati'),
(154, 'st', 'Sotho, Southern', 'sotho du Sud'),
(155, 'su', 'Sundanese', 'soundanais'),
(156, 'sv', 'Swedish', 'su&#233;dois'),
(157, 'sw', 'Swahili', 'swahili'),
(158, 'ta', 'Tamil', 'tamoul'),
(159, 'te', 'Telugu', 't&#233;lougou'),
(160, 'tg', 'Tajik', 'tadjik'),
(161, 'th', 'Thai', 'tha&#239;'),
(162, 'ti', 'Tigrinya', 'tigrigna'),
(163, 'tk', 'Turkmen', 'turkm&#232;ne'),
(164, 'tl', 'Tagalog', 'tagalog'),
(165, 'tn', 'Tswana', 'tswana'),
(166, 'to', 'Tonga (Tonga Islands)', 'tongan (&#206;les Tonga)'),
(167, 'tr', 'Turkish', 'turc'),
(168, 'ts', 'Tsonga', 'tsonga'),
(169, 'tt', 'Tatar', 'tatar'),
(170, 'tw', 'Twi', 'twi'),
(171, 'ty', 'Tahitian ', 'tahitien'),
(172, 'ug', 'Uighur; Uyghur', 'ou&#239;gour'),
(173, 'uk', 'Ukrainian', 'ukrainien'),
(174, 'ur', 'Urdu', 'ourdou'),
(175, 'uz', 'Uzbek', 'ouszbek'),
(176, 've', 'Venda', 'venda'),
(177, 'vi', 'Vietnamese', 'vietnamien'),
(178, 'vo', 'Volap&#252;k', 'volap&#252;k'),
(179, 'wa', 'Walloon', 'wallon'),
(180, 'wo', 'Wolof', 'wolof'),
(181, 'xh', 'Xhosa', 'xhosa'),
(182, 'yi', 'Yiddish', 'yiddish'),
(183, 'yo', 'Yoruba', 'yoruba'),
(184, 'za', 'Zhuang; Chuang', 'zhuang; chuang'),
(185, 'zh', 'Chinese', 'chinois'),
(186, 'zu', 'Zulu', 'zoulou');
