CREATE TABLE IF NOT EXISTS `orbx_mod_estate` (
  `id` int(11) NOT NULL auto_increment,
  `title` text NOT NULL,
  `description` text NOT NULL,
  `msquare` decimal(12,2) NOT NULL,
  `category` varchar(255) NOT NULL,
  `ad_type` varchar(255) NOT NULL,
  `price` decimal(12,2) NOT NULL,
  `currency` varchar(255) NOT NULL,
  `county` varchar(255) NOT NULL,
  `street` varchar(255) NOT NULL,
  `street_no` varchar(255) NOT NULL,
  `post_num` varchar(255) NOT NULL,
  `logitude` varchar(255) NOT NULL,
  `latitude` varchar(255) NOT NULL,
  `house_type` varchar(255) NOT NULL,
  `build_type` varchar(255) NOT NULL,
  `year_built` varchar(255) NOT NULL,
  `msquare_backyard` varchar(255) NOT NULL,
  `room_num` varchar(255) NOT NULL,
  `floor_num` varchar(255) NOT NULL,
  `bath_num` varchar(255) NOT NULL,
  `heating` varchar(255) NOT NULL,
  `equipment` bigint(20) NOT NULL,
  `docs` varchar(255) NOT NULL,
  `tags` text NOT NULL,
  `user_id` int(11) NOT NULL,
  `status` tinyint(1) NOT NULL default '1',
  `pics` text NOT NULL,
  `pic_main` text NOT NULL,
  `video` text NOT NULL,
  `public_transport` text NOT NULL,
  `sponsored` tinyint(1) NOT NULL default '0',
  `submited` int(11) NOT NULL default '0',
  `permalink` varchar(255) NOT NULL,
  `menu` text NOT NULL,
  `business_type` varchar(255) NOT NULL,
  `apartment_type` varchar(255) NOT NULL,
  `land_type` varchar(255) NOT NULL,
  `length` varchar(255) NOT NULL,
  `width` varchar(255) NOT NULL,
  `sea_distance` varchar(255) NOT NULL,
  `bed_num` varchar(255) NOT NULL,
  `flat_num` varchar(255) NOT NULL,
  `flat` varchar(255) NOT NULL,
  `town` text NOT NULL,
  `neighborhood` text NOT NULL,
  `keywords` text NOT NULL,
  `zg` varchar(255) NOT NULL,
  `publish_print` tinyint(1) NOT NULL default '0',
  `preview` tinyint(1) NOT NULL default '0',
  `video_embed` text NOT NULL,
  `sponsored_category` text NOT NULL,
  `sponsored_live_to` int(11) NOT NULL default '0',
  `views` int(11) NOT NULL default '0',
  `ip` text NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `status` (`status`),
  KEY `submited` (`submited`),
  KEY `sponsored` (`sponsored`),
  KEY `category` (`category`),
  KEY `county` (`county`),
  KEY `user_id` (`user_id`),
  KEY `permalink` (`permalink`),
  FULLTEXT KEY `title` (`title`),
  FULLTEXT KEY `description` (`description`),
  FULLTEXT KEY `neighborhood` (`neighborhood`),
  FULLTEXT KEY `town` (`town`),
  FULLTEXT KEY `menu` (`menu`)
) ;

CREATE TABLE `orbx_mod_estate_user_flags` (
  `id` int(11) NOT NULL auto_increment,
  `ad_id` int (11) NOT NULL default '0',
  `user_rid` int (11) NOT NULL default '0',
  `type` int(1) NOT NULL default '0',
  PRIMARY KEY  (`id`)
) ;